<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CaveContentDisplay</AssemblyName>
    <RootNamespace>CaveContentDisplay</RootNamespace>
    <Version>1.1.2</Version>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GamePath>E:\Idan's\Game\StardewValley</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
  </ItemGroup>

</Project>

